version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:lastest
   steps:
      - run:
          name: OS setup 
          command: export DEBIAN_FRONTEND=noninteractive; export TZ=Asia/Kolkata; apt -qq update --fix-missing; apt -qq install -y git wget make
      - run:
          name: get basic setup
          command: wget https://raw.githubusercontent.com/Ankits-lab/hycon_bot/master/setup.sh
          no_output_timeout: 8h
      - run:
          name: build basic setup
          command: bash setup.sh
          no_output_timeout: 8h
      - run:
          name: get bot code
          command: wget https://raw.githubusercontent.com/Ankits-lab/hycon_bot/master/deploy.sh
          no_output_timeout: 8h
      - run:
          name: run bot
          command: bash deploy.sh
          no_output_timeout: 8h

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
